name: Agenda

on:
  schedule:
    - cron: "0 22 * * 0"  # it will run at 22:50 PM Lisbon time in Sunday
    
jobs:
  validate-context:
    name: Validate workflow context
    runs-on: ubuntu-latest
    steps:
      - name: Determine branch from schedule
        id: inventory
        shell: bash
        run: |
          if [ "${{ github.event.schedule }}" == "0 22 * * 0"  ]; then
            echo "OK!!"
          else
            echo "NOK!!"
          fi
          
          
          