name: Teste

on:
  schedule:
    - run: |
        current_time="$(TZ=Europe/Lisbon date '+%H:%M')"
        if [ $current_time == "16:00" ]; then
          echo "Current time is $current_time"
        fi

        echo "$current_time" >> GITHUB_OUTPUT
    - cron: ${{ github.event.schedule.outputs.current_time }}

jobs:
  validate-context:
    name: Validate workflow context
    runs-on: ubuntu-latest
    steps:
      - name: Determine current time
        shell: bash
        run: |
          echo "Current time is ${{ github.event.schedule.outputs.current_time }}"