name: Teste de agendamento

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  validate-context:
    name: Validate workflow context
    runs-on: ubuntu-latest
    steps:
      - name: Determine hour executed from schedule
        id: inventory
        shell: bash
        run: |
          echo "Este workflow foi disparado pelo agendamento do GitHub Actions às $(date +'%H:%M:%S')"
