name: Teste

on:
  schedule:
    - cron: "0 22 * * *" # dev
    - cron: "10 22 * * *" # dev

jobs:
  validate-context:
    name: Validate workflow context
    runs-on: ubuntu-latest
    steps:
      - name: Get branch to consider
        id: getBranch
        shell: bash
        run: |
          if [ "${{ github.event.schedule }}" = "0 22 * * *" ]; then
            branch="dev" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.schedule }}" = "10 22 * * *" ]; then
            branch="qual" >> $GITHUB_OUTPUT
          fi

          echo "Nothing to do for schedule!!"

      - name: Checkout branch to consider
        uses: actions/checkout@v7
        with:
          repository: ${{ github.repository }}
          ref: ${{ steps.getBranch.outputs.branch }}
          show-progress: true

      - name: Show README content
        run: |
          cat README.md
